{
 "title": "Formula1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "McLaren",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 0 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   }
  },
  {
   "title": "Position Tracker",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 9, "w": 10, "x": 7, "y": 0 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   }
  },
  {
   "title": "Lap Number",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  lapnumber\r\nFROM doc.etcar\r\nORDER BY time_index DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  speed\r\nFROM doc.etcar\r\nORDER BY time_index DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  rpm\r\nFROM doc.etcar\r\nORDER BY time_index DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  speed\r\nFROM doc.etcar\r\nWHERE speed IS NOT NULL\r\nORDER BY time_index ASC;\r\n"
    }
   ]
  },
  {
   "title": "DRS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  drs\r\nFROM doc.etcar\r\nORDER BY time_index DESC\r\nLIMIT 1;\r\n"
    }
   ]
  }
 ]
}