version: '3'
services:
  threejs-server:
    image: nginx:alpine
    container_name: threejs-nginx
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
